language: bash

services: docker

env:
  global:
    - secure: "UbTz8M9r+mOGBdeDGmUNpBioLq3Z7ucJuhydukJqQYARc2xyDZHK++HjGQNvaqcsc+uudCVxcIR5QQZcxM7qAyUxsxbmZ3r4WqTBkY3PTLcGzdK47LIhGshXV7KajEEI7dm52b84N/MnOWhxIUQJ5AAUhJQzZBseNUKZVFkmTAOJ9KbgyvisqDCqzu+haGTCpaMIFCRDM23M0xyrLAva8x3aqTxcVErS+J6x7u3GIVNds5eDZrbK11y/kY0A1ZrWvELXsF63Xcv1E75nHiZV+wFc8xhVorFqnN7dvBrRIzm1LxdFev8Gt7yXdkLM/iQeOE8pDK1iSnvU/hn8fWKXyJY0N+VSgeQDVGjtr18E5ZISDgM+Zcr5Hhv9jpMF3ORFsc1HzODMcIPpTpku7o9YOZ3ahNQeC8XEtxaq/UfaLikwt8SK4JKfI5K7rFDFa8r7lg5VkGIX9EfdfY6P86a69sQAQMWP++RrP09eOHPMxypE7O26hR+zXbfFwd9FblGUeds59R1G+b/AOyT3tjqDXMt7irWucv9jIswScOUAcYfYEtxyHhqkCHy195U5DYT136PgASJLhYmcTotd7D3RDG2rtdkT/3t296YD/spmEbmgGezckcexwoEGmQOrulcnNDAPB04vMXSWp0DS+bMYQLEUWQDVz9sO+1NuUOXf49c="
    - secure: "W7QpBqCmqceedLcTMZXDIuHGBY3NIi/SsSFKd0CMKe2dPdgn2RyknzfV8LEVfOGJ3Gpe9LSWTyPp88oFB6chX1y7ZYdjkALJAQCqvtC4OjfpCLo4KCRZP+VjSw2i7UHsu3DGxA5/X7x6B2cbVHZJKUulszNteo7jyZJsevDn4I4uB/bQj+QkRLuiadBy6eAD87k23RJjw7Xylnde2Umev3/KU6CD9Wxis6Yj56k8A5J3IUWEqK0iDYgX/V/LoWWcekc8cO1Bj3EA7V9CxVizxLGccFkf4go78/fhJ3bHf13fWSQXu7ytGvhIO0USRI+KaEv1CFxNDYwyjglvm9kLN+t6uaF5XJkQvMfdESn3NhdeuqsKmm3P7eUU5eA1ewnVreSXUATntQOHbDyGKs4eK9Nxrhw7JeFgIiIgyXdoxnVMl5L4c7SBq7hyfZ30QIx5Hxzzsz2nxLleL1vyndjXTPDW0mFkBLVVnrYmpYQa80VltSZFWaW03dq/BDywLwWxsC08tuUvnv1ayZmLxVBhIuXs43EM+LQg5gAYKcetS5cxNw6KKvWZk8eI7X9hPewQiQqx5wQpTkA+F0SrUKN7ePqe/H9deI46fE958GUZnopnXA9vRYgUoz930MW7eet1k4oINcoLRD9F8B2S55oLlMkAe2IXoqCDwBmiTHAdEB0="
  matrix:
    - VERSION=8.5
    - VERSION=9.1
    - VERSION=12.18
    - VERSION=14.4
    - VERSION=latest VERSION_ALIAS=14.4

before_script:
  - if [[ "$VERSION" != "latest" ]]; then cd "src/$VERSION"; fi
  - if [[ "$VERSION" == "latest" ]]; then cd "src/$VERSION_ALIAS"; fi
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
