name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-node14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          VERSION=14
          IMAGE_NAME="chesszebra/$(echo "$GITHUB_REPOSITORY" | cut -c 25-):${VERSION}"
          cd src/$VERSION
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  build-node15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          VERSION=15
          IMAGE_NAME="chesszebra/$(echo "$GITHUB_REPOSITORY" | cut -c 25-):${VERSION}"
          IMAGE_NAME_LATEST="chesszebra/$(echo "$GITHUB_REPOSITORY" | cut -c 25-):latest"
          cd src/$VERSION
          docker build -t $IMAGE_NAME -t $IMAGE_NAME_LATEST .
          docker push $IMAGE_NAME
          docker push $IMAGE_NAME_LATEST
